#!/usr/bin/python
import eeprom, sys, os

with open(sys.argv[1], 'rb') as f:
    image = eeprom.Reader(f)

print('eeprom version: %s (%s)' % (image.version, image.image_type))
print('-----------------------------------')
for chunk in image:
    with open(os.path.join(sys.argv[2], chunk.name or 'boot'), 'wb') as out:
        if isinstance(chunk, (eeprom.ChunkFile,)):
            out.write(chunk.get_file())
        else:
            out.write(chunk.get_raw_bin())


